apiVersion: v1
kind: Service
metadata:
  name: quiz-app-main-backend-svc
  labels:
    app: quiz-app-main-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: quiz-app-main-backend
